spring:
  application:
    name: 'springsecuritybasic'
  security:
    user:
      name: 'eazybytes'
      password: '12345'

logging:
  level:
    org:
      springframework:
              security: DEBUG
